version: 1.0.0.{build}

configuration: Debug
platform: Any CPU

install:
  - cmd: nuget restore

environment:
  COVERALLS_REPO_TOKEN:
    secure: CtNjB3/AUTKeFrXmEpR71u6zUBqp2z1/bESLf1LRoZvIQhRnuJEqc5GXELWVHKMI

build:
  project: HtmlKit.sln
  verbosity: minimal
