version: 1.0.0.{build}

configuration: Debug
platform: Any CPU

install:
  - cmd: nuget restore

environment:
  COVERALLS_REPO_TOKEN:
    secure: CtNjB3/AUTKeFrXmEpR71u6zUBqp2z1/bESLf1LRoZvIQhRnuJEqc5GXELWVHKMI

build:
  project: HtmlKit.sln
  verbosity: minimal

test_script:
- ps: >-
    $testDir = ".\UnitTests\bin\Debug\"

    $tests = @("$testdir\UnitTests.dll")

    foreach ($elem in $tests) {
    	.\packages\OpenCover.4.5.3723\OpenCover.Console.exe `
    	-register:user `
    	-target:.\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe `
    	"-targetargs: ""$elem"" /framework:net-4.5 /noshadow" `
    	"-filter:+[HtmlKit]* -[UnitTests]* -[CodeGenerator]*" `
    	-output:opencover.xml `
    }

    $revision = git rev-parse HEAD

    $branch = git rev-parse --abbrev-ref HEAD

    $commitAuthor = git show --quiet --format="%aN" $revision

    $commitEmail = git show --quiet --format="%aE" $revision

    $commitMessage = git show --quiet --format="%s" $revision

    .\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe `
    --opencover -i opencover.xml `
    --repoToken $Env:COVERALLS_REPO_TOKEN `
    --commitId $revision `
    --commitBranch $branch `
    --commitAuthor $commitAuthor `
    --commitEmail $commitEmail `
    --commitMessage $commitMessage `
    --useRelativePaths `
    --basePath .\UnitTests\bin\Debug
